[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 500
runOnSave = true

[browser]
gatherUsageStats = false

[client]
showErrorDetails = false

[theme]
base = "light"
primaryColor = "#3b82f6"
