[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[client]
toolbarMode = "viewer"
showErrorDetails = false

[theme]
base = "light"
primaryColor = "#3b82f6"
